name: Build

on:
  push:

env:
  FE1_PATHS: |
    apps/fe1
    tools
  FE2_PATHS: |
    apps/fe2
    tools

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      fe1_changed: ${{ steps.filter.outputs.fe1_changed }}
      fe2_changed: ${{ steps.filter.outputs.fe2_changed }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Output Github context
        env:
          CONTEXT: ${{ toJson(github) }}
        run: |
          echo "Github context: $CONTEXT"

      - name: Filter which workflows to run
        id: filter
        env:
          PREVIOUS_COMMIT: ${{ github.event.before }}
        run: |
          echo "Checking for changes in frontend apps..."

          if [[ "$GITHUB_REF_NAME" != "main" ]]; then
            BASE_REF="${PREVIOUS_COMMIT}"
            HEAD_REF="$GITHUB_SHA"
            git diff --name-only $BASE_REF $HEAD_REF > changed_files.txt
          else
            git diff --name-only origin/main~1 origin/main > changed_files.txt
          fi

          for var in FE1_PATHS FE2_PATHS; do
            changed=false
            while read -r path; do
              [[ -z "$path" ]] && continue
              grep -q "^$path" changed_files.txt && changed=true && break
            done <<< "${!var}"
            key=$(echo "$var" | tr '[:upper:]' '[:lower:]' | sed 's/_paths//')
            echo "$key"_changed=$changed >> $GITHUB_OUTPUT
          done

  build-fe1:
    needs: detect-changes
    if: needs.detect-changes.outputs.fe1_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    env:
      WORKING_DIRECTORY: apps/fe1
    steps:
      - name: Checkout frontend directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.WORKING_DIRECTORY }}
          sparse-checkout-cone-mode: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build frontend app
        run: npm run build

  build-fe2:
    needs: detect-changes
    if: needs.detect-changes.outputs.fe2_changed == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}
    env:
      WORKING_DIRECTORY: apps/fe2
    steps:
      - name: Checkout frontend directory
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.WORKING_DIRECTORY }}
          sparse-checkout-cone-mode: false
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build frontend app
        run: npm run build
